#!/bin/bash

appId=`cat app/build.gradle | grep "applicationId '" | head -n 1 | cut -d "'" -f 2`

echo "Uninstalling $appId".debug

if [[ $1 == "e" || $1 == "d" ]]; then
  adb -$1 uninstall $appId.debug
else
  adb uninstall $appId.debug
fi
